# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 839dc5d160e614b55dc42742867091cb062192582d021b3342d31c6f9ca27ba81aef0e31df6be07835df7b8238866e02a6f2b3cba9459f9da9a1f6432c46440e

test:
  secret_key_base: 4e262797935e612a3642fc40cc76bed3b42d417fe4b64928f8f106ac60016263c4a7f1daea66ec2504d258a9163ef854974ee4f82e070f28f7bf702e41ccf103

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
